---
version: '2'
services: 
  mysqldb:
    extends:
      file: 'docker-compose.yml'
      service: mysqldb
    environment:
      - MYSQL_DATABASE=transaction_api_test
      - MYSQL_ROOT_PASSWORD=root