swagger: '2.0'
info:
  description: "Microservice for incoming transactions"
  version: "1.0.0"
  title: "Microservice transaction api"
  contact:
    email: "murtaza@digitalefactuur.nl"

host: "192.168.88.101"
basePath: "/api"


schemes:
- "http"

securityDefinitions:
  bearerAuth:            # arbitrary name for the security scheme
    type: apiKey
    in: header
    name: Authorization
    description: "Use the JWT Bearer format: `Bearer JWT_TOKEN`"

# To apply Basic auth to the whole API:
security:
  - bearerAuth: []

components:
  schemas:
    States:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name: 
          type: "string"
        description: 
          type: "text"



externalDocs:
  description: "Find out more about Bank Export Converter"
  url: "https://github.com/kantoor-f12/transactions_api"